AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: 'thomas-rauffenbart-crc-SAM-update2'

Mappings:
    EnvVariables:
      stage:
        Dev:
           var1: user1
           TableName: toms-crc-SAMCICD-Dev
        prod2:
           var1: user2
           TableName: toms-crc-SAMCICD-prod2

Resources:

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !FindInMap [ EnvVariables, ${paramEnvironment}, TableName ] 
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: "ID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "ID"
          KeyType: "HASH"

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !FindInMap [ EnvVariables, ${paramEnvironment}, TableName ]
      CodeUri: s3://thomasrauffenbartresume2022/app.py.zip
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        Visits:
          Type: Api
          Properties:
            Path: /visit
            Method: post
