version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::288422731667:user/aws-sam-cli-managed-Prod-prod-pipelin-PipelineUser-QV3S4JNA6TD8"
permissions_provider = "AWS IAM"

[Dev]
[Dev.pipeline_bootstrap]
[Dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::290776742082:role/aws-sam-cli-managed-Dev-pipe-PipelineExecutionRole-1KRFBYI5BU88F"
cloudformation_execution_role = "arn:aws:iam::290776742082:role/aws-sam-cli-managed-Dev-p-CloudFormationExecutionR-2GD724TQGX63"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-vsjvsbqrqxw6"
image_repository = ""
region = "us-east-1"

[Prod]
[Prod.pipeline_bootstrap]
[Prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::288422731667:role/aws-sam-cli-managed-Prod-pip-PipelineExecutionRole-RDAN1WI7MY8M"
cloudformation_execution_role = "arn:aws:iam::288422731667:role/aws-sam-cli-managed-Prod-CloudFormationExecutionR-5UBXEJ50HVE3"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-1xvi0jrl1v4qx"
image_repository = ""
region = "us-east-1"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::290776742082:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-B5QSV5A0OYGN"
cloudformation_execution_role = "arn:aws:iam::290776742082:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-PKPR66EM8C67"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1661a514yrja5"
image_repository = ""
region = "us-east-1"

[prod2]
[prod2.pipeline_bootstrap]
[prod2.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::290776742082:role/aws-sam-cli-managed-prod2-pi-PipelineExecutionRole-1WNRSTYV0CFOK"
cloudformation_execution_role = "arn:aws:iam::290776742082:role/aws-sam-cli-managed-prod2-CloudFormationExecutionR-I9H140GDCQEC"
artifacts_bucket = "aws-sam-cli-managed-prod2-pipelin-artifactsbucket-x6ahootkrrj9"
image_repository = ""
region = "us-east-1"

[Prod-prod]
[Prod-prod.pipeline_bootstrap]
[Prod-prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::288422731667:role/aws-sam-cli-managed-Prod-pro-PipelineExecutionRole-1ONZW1NOV037Y"
cloudformation_execution_role = "arn:aws:iam::288422731667:role/aws-sam-cli-managed-Prod-CloudFormationExecutionR-1S1LKW0NPLOIS"
artifacts_bucket = "aws-sam-cli-managed-prod-prod-pip-artifactsbucket-1pzpeejqc0h3g"
image_repository = ""
region = "us-east-1"

[prod-account]
[prod-account.pipeline_bootstrap]
[prod-account.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::288422731667:role/aws-sam-cli-managed-prod-acc-PipelineExecutionRole-S298R97YDAJH"
cloudformation_execution_role = "arn:aws:iam::288422731667:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-7HBKO2HEGIHJ"
artifacts_bucket = "aws-sam-cli-managed-prod-account-artifactsbucket-1mz5dhwied45m"
image_repository = ""
region = "us-east-1"
