version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crc-12-13"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1i5n25im2u6rd"
s3_prefix = "crc-12-13"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
